name: torugo_util
description: Library with useful classes and methods.
version: 1.0.0
repository: https://github.com/vitor-hugo/dart-util

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
